### ISSUE TITLE
Transfer ownership to @cmeeren

### ISSUE THREAD

**Issue by moodmosaic** [cmeeren/fsharp-hedgehog-experimental#30]
Given that

* @cmeeren has done most (if not *all*) of the hard work on fsharp-hedgehog-experimental
* my spare time is *extremely* limited when it comes to maintaining fsharp-hedgehog-experimental

I suggest that we

* transfer fsharp-hedgehog-experimental to @cmeeren 🎉 🚀 

**Advantages**

Transferring this repository to @cmeeren can make it move a little bit faster, as right now the issues and the pull requests can be blocked several weeks waiting feedback from us.

Of course, I'm more than happy to help with any questions on issues and pull requests (given that I have the answer(s)), but I will no longer be the *maintainer* of this repository.

By *not* being the maintainer of fsharp-hedgehog-experimental, I may put my (limited) spare time into fsharp-hedgehog itself and even the Haskell version (where we're missing the diehard tests, for example).

**Disadvantages**

Are there any?

**Practical issues**

I'd really like this repository to be moved to @cmeeren's GitHub, (mine or some other's, if @cmeeren isn't willing to take over).

Moving fsharp-hedgehog-experimental outside @hedgehogqa amplifies that fact that this repository is all about taking great ideas from the community and grouping them altogether for trying them out, like:

* https://hackage.haskell.org/package/quickcheck-property-comb
* https://hackage.haskell.org/package/quickcheck-properties
* https://hackage.haskell.org/package/quickcheck-arbitrary-adt
* https://hackage.haskell.org/package/quickcheck-simple
* etc.

---

I've discussed this with @jystic and he's positive, so we really look forward your decision @cmeeren 🥇

**Comment by cmeeren** [comment]
Thanks for the confidence! My time too is severely limited, so I will need to give this some careful thought. If the repo gets too much activity, I won't be able to handle it well (in other words, the situation in which you currently find yourself).

**Comment by moodmosaic** [comment]
Well, it's also going to be up to you how much activity you want (depending on how much you talk about this on Twitter, blog posts, etcetera).

Right now it's almost exclusive *you* 🚀, so at least you should be able to move it fast to the direction you wish ❤️

**Comment by cmeeren** [comment]
Certainly. From a community standpoint, the goal should IMHO always be too much activity 😅 Though someone else would have to arrange for publicity, because I don't use Twitter actively and don't have much reach on my personal blog.

In any case, I'd be more comfortable if CI/CD was set up and we had a Nuget package out.

What are your thoughts on the build pipeline? I've basically only ever used plain VS solutions and NuGet, no explicit build scripts or FAKE or even Paket. Do all that give us anything here? Is there any reason not to play it simple with this particular project by for example creating a new solution with .NET Standard projects and using NuGet for references, with no FAKE or other build steps?

**Comment by moodmosaic** [comment]
You can get rid of `build.fsx` and just use `dotnet` as @porges did in https://github.com/hedgehogqa/fsharp-hedgehog/pull/153 for .NET Standard.

**Comment by moodmosaic** [comment]
You can of course setup Travis CI, and publish NuGet packages, if you wish. These aren't setup yet, but if you look in https://github.com/hedgehogqa/fsharp-hedgehog/pull/153, it has all the information you need.

**Comment by cmeeren** [comment]
Thanks, I'll have a look (probably not until the end of the week).

I suppose I'll also be free to use whatever code style I'm most comfortable with?

**Comment by moodmosaic** [comment]
>Thanks, I'll have a look (probably not until the end of the week).

👍 

>I suppose I'll also be free to use whatever code style I'm most comfortable with?

Sure, why not.

So, may we proceed with @jystic and transfer fsharp-hedgehog-experimental to your GitHub account?

**Comment by moodmosaic** [comment]
>so I will need to give this some careful though

(Yep, no need to decide exactly right now.)

**Comment by cmeeren** [comment]
Go ahead and transfer.

Did you create a NuGet package that also needs to be transferred? Anything else?

**Comment by moodmosaic** [comment]
@jystic should be able to transfer it to you (he's the owner of the org).— I haven't created a NuGet package, but feel free to make your own. It can be similar to https://github.com/hedgehogqa/fsharp-hedgehog/pull/153.

**Comment by moodmosaic** [comment]
Hmm, it looks like transferring from a GitHub *Org* to a regular GitHub *username* is a bit tricky:

![image](https://user-images.githubusercontent.com/287532/36640586-891cc818-1a2a-11e8-8012-1558654c6995.png)
 
---

According to that message from GitHub, I must first transfer this to myself and then to @cmeeren. Let's see if this will work out. /cc @jystic

**Comment by moodmosaic** [comment]
That seemed to work:

![image](https://user-images.githubusercontent.com/287532/36640606-045f518a-1a2b-11e8-9c8b-ffdd1eb71c87.png)

---

I can confirm that navigating to
https://github.com/hedgehogqa/fsharp-hedgehog-experimental/

successfully redirects to the new, temporary, location
https://github.com/moodmosaic/fsharp-hedgehog-experimental

(Also, I'm writing this comment on the new location.) /cc @jystic @cmeeren 

---

I'm about to transfer this now to @cmeeren.

**Comment by moodmosaic** [comment]
After @cmeeren accepts the transfer, we should be all set.

![image](https://user-images.githubusercontent.com/287532/36640642-afa7c018-1a2b-11e8-876e-9e9903e5915f.png)

/cc @jystic

**Comment by cmeeren** [comment]
Done!

**Comment by moodmosaic** [comment]
:-1:

**Comment by moodmosaic** [comment]
:+1:

**Comment by moodmosaic** [comment]
Oops, I meant  :+1:

**Comment by cmeeren** [comment]
Just wondering, is there any reason not to switch from Paket to Nuget for this project? I find Nuget easier to work with in VS, and with new-style project files, dependencies are even transitive.

And another thing - when I release a nuget, should I pin the dependency on Hedgehog in any way? Does Hedgehog follow semver?

**Comment by cmeeren** [comment]
And another thing: Do any of you want to be removed from the author/copyright list? (I'm asking just as a courtesy; I have no problems with how it currently is).

**Comment by moodmosaic** [comment]
It should be perfectly fine to get rid of `.paket.template` and build the NuGet Package through the `dotnet` command. If you get rid of Paket, you may also get rid of `.paket.dependencies` and `.paket.reference` files.

Otherwise, you can use `dotnet` and `paket pack` as @porges did in https://github.com/hedgehogqa/fsharp-hedgehog/pull/153 for .NET Standard. IIRC, `paket pack` sets the metadata for the NuGet Package by reading the [`.paket.template`](https://github.com/hedgehogqa/fsharp-hedgehog/blob/75b985dc00fd530ab0cef1ba417e62017c89da58/src/Hedgehog/paket.template).

**Comment by cmeeren** [comment]
Thanks. I think I'll just go ahead and create a new solution/projects and copy over the old code. That'll probably be the simplest way to get things over to .NET Standard, nuget and new fsproj format.

**Comment by moodmosaic** [comment]
>(I'm asking just as a courtesy; I have no problems with how it currently is

Thank you for asking. I don't mind being included, but I think your name should go first on the [`LICENSE`](https://github.com/cmeeren/fsharp-hedgehog-experimental/blob/78c6cf5eb2143337eeb14591c3df346ed39e6537/LICENSE) file.

**Comment by moodmosaic** [comment]
>Does Hedgehog follow SemVer?

It does, however it's on [Major version zero (0.y.z)](https://semver.org/#spec-item-4).

You may just reference the latest version of Hedgehog. We're trying not to introduce (unnecessary) breaking changes anyway. In case we do, we should address the issue(s) there, or here.

---

We also have a Slack channel for Hedgehog, let me know if you want to be in 😃 (I can happily invite you in, using the email I see on your git commits).

**Comment by cmeeren** [comment]
> We also have a Slack channel for Hedgehog, let me know if you want to be in 😃

Sure, go ahead. :)

**Comment by moodmosaic** [comment]
Done :)

**Comment by cmeeren** [comment]
Finally published to NuGet  through AppVeyor. :) Some fiddling was necessary, but the end result (regarding CI/testing/deployment/.NET Standard) is fairly clean. Perhaps some things can be simplified in Hedgehog too.

Hedgehog.Experimental requires .NET Standard 2.0 by the way, due to some dependencies (TypeShape IIRC).

**Comment by moodmosaic** [comment]
👍

**Comment by cmeeren** [comment]
And now there's some brief documentation/examples in the readme, too. In short, we're ready to roll! Feel free to spread the word.

**Comment by moodmosaic** [comment]
I'll do when I'm home :)

**Comment by moodmosaic** [comment]
I've re retweeted your [tweet](https://twitter.com/cmeeren/status/968189957310468098) 😃 Let me know if I can do something more 😅 

Once again, thank you for all the hard work you've been putting in 💯 ❤️
