### ISSUE TITLE
GenX.auto fails with anything involving uint64

### ISSUE THREAD

**Issue by marklam** [cmeeren/fsharp-hedgehog-experimental#32]
e.g.
```F#
let! foo = GenX.auto<uint64>
```
Fails with
```
System.Exception : Class System.UInt64 lacking an appropriate ctor
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
…
   at Hedgehog.Property.Delay@221-1.Invoke(Unit x)
   at Hedgehog.Gen.Delay@21.Invoke(Unit x)
   at Hedgehog.Random.delay@17.Invoke(Seed seed, Int32 size)
   at Hedgehog.Property.loop@332-21(Int32 n, Random`1 random, Seed seed, Int32 size, Int32 tests, Int32 discards)
   at Hedgehog.Property.Report(Int32 n, Property`1 p)
   at Hedgehog.Property.Check(Property`1 p)
```

This also affects discriminated unions with uint64 cases.

**Comment by cmeeren** [comment]
This is a Hedgehog bug, see https://github.com/hedgehogqa/fsharp-hedgehog/issues/185

**Comment by cmeeren** [comment]
Oh wait, I mixed `int64` and `uint64`.

**Comment by cmeeren** [comment]
Should be released shortly in v0.1.2.

**Comment by marklam** [comment]
Doesn't seem to fix the problem. I've created a pull request with a failing test.

**Comment by cmeeren** [comment]
Sorry, I was a bit too quick on the trigger. I've fixed it, but now I'm hitting upstream bug hedgehogqa/fsharp-hedgehog#185 which still need to be fixed. I've removed your unit test again so that the CI completes and I have released 0.1.3, but you can't generate any int64 stuff at all using Hedgehog until that bug is fixed.

**Comment by marklam** [comment]
Unfortunately, this and #31 aren't fixed for clients of hedgehog-experimental until this package is rebuilt.

This is because the scaling functions I changed in hedgehog were inline functions (for SRTP) - so any uses of the (U)Int64 generators that come from inside hedgehog-experimental still have the unfixed scaling baked-in.

**Comment by cmeeren** [comment]
0.1.4 is in the pipeline, should work there.
